services:
  database:
    image: "postgres:16.15-alpine3.24"
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app

  status_api:
    build:
      context: ./status_api
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  pgdata:
