spring:
  application:
    name: status-api

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

django:
  app:
    url: ${DJANGO_APP_URL:http://django:8000}

springdoc:
  swagger-ui:
    path: /
